-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.countries
(
    code character varying(2) COLLATE pg_catalog."default" NOT NULL,
    continent_code character varying(2) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    iso3 character varying(3) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "number" character varying(3) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT countries_pkey PRIMARY KEY (code)
);

CREATE TABLE IF NOT EXISTS public.film
(
    id bigint NOT NULL,
    date_added_todb date,
    length_in_minutes integer NOT NULL,
    poster_path character varying(255) COLLATE pg_catalog."default",
    release_year integer,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT film_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.film_countries
(
    film_id bigint NOT NULL,
    country_code character varying(2) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT film_countries_pkey PRIMARY KEY (film_id, country_code)
);

CREATE TABLE IF NOT EXISTS public.film_genres
(
    film_id bigint NOT NULL,
    genre_id bigint NOT NULL,
    CONSTRAINT film_genres_pkey PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS public.film_job_person
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    film_id bigint,
    job_id bigint,
    person_id bigint,
    CONSTRAINT film_job_person_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.film_movielist
(
    movie_list_id bigint NOT NULL,
    film_id bigint NOT NULL,
    CONSTRAINT film_movielist_pkey PRIMARY KEY (movie_list_id, film_id)
);

CREATE TABLE IF NOT EXISTS public.genres
(
    id bigint NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT genres_pkey PRIMARY KEY (id),
    CONSTRAINT ukpe1a9woik1k97l87cieguyhh4 UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.job
(
    id bigint NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT job_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.log
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date date NOT NULL,
    first_watch boolean NOT NULL,
    rating real,
    review character varying(255) COLLATE pg_catalog."default",
    film_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.movie_list
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_watchlist boolean,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT movie_list_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.password_reset
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    used boolean NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT password_reset_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.person
(
    id bigint NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    profile_path character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT person_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    username character varying(14) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username)
);

ALTER TABLE IF EXISTS public.film_countries
    ADD CONSTRAINT fkoc0ckl9ejlj1cqx7thp601jrm FOREIGN KEY (film_id)
    REFERENCES public.film (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.film_countries
    ADD CONSTRAINT fkpwmsutbakiic1b9p628fqig33 FOREIGN KEY (country_code)
    REFERENCES public.countries (code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.film_genres
    ADD CONSTRAINT fkk28yrhtqd5w6geyhkj6f2dd5u FOREIGN KEY (genre_id)
    REFERENCES public.genres (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.film_genres
    ADD CONSTRAINT fktke72661p7jjfc48frtcclygv FOREIGN KEY (film_id)
    REFERENCES public.film (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.film_job_person
    ADD CONSTRAINT fk63l8ch3wmdxpl3tgxdx0553t9 FOREIGN KEY (person_id)
    REFERENCES public.person (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.film_job_person
    ADD CONSTRAINT fkf0nhja7imnakijtbjnk3xerls FOREIGN KEY (film_id)
    REFERENCES public.film (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.film_job_person
    ADD CONSTRAINT fknlgsyk7gfl88h3emyn845q8tx FOREIGN KEY (job_id)
    REFERENCES public.job (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.film_movielist
    ADD CONSTRAINT fk3mlvitx4ylh8x6f1kjnri82lv FOREIGN KEY (film_id)
    REFERENCES public.film (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.film_movielist
    ADD CONSTRAINT fkeos2273pouvvgheowmb1tk9lm FOREIGN KEY (movie_list_id)
    REFERENCES public.movie_list (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.log
    ADD CONSTRAINT fkefuitn33qkpy6nonixjyyu3u0 FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.log
    ADD CONSTRAINT fkk1ui3le07jsiktxj7279qg9uh FOREIGN KEY (film_id)
    REFERENCES public.film (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.movie_list
    ADD CONSTRAINT fk4cfqrcyhekvlokii0vcww35bf FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.password_reset
    ADD CONSTRAINT fk74ayk4gy7j9k9caxg9pb7k1wa FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;